### ISSUE TITLE
読者が本を出品して購入することができるようにするUIの設計と機能の実装

### ISSUE THREAD

**Issue by taijusanagi** [block-base/bazaaar.io#84]
### 目的
できれば読者には、読み終わってよかった→宣伝したい→宣伝して他の人に読んでもらうために出品する、という体験をして欲しいので、その体験の実現がこのIssueでやりたいことです。

読者が本を出品し、出品したアセットが売れると、購入者が手数料を払ってSwapが発生するようなイメージです。

### 内容
最初に考えた感じだと下記のイメージです

- UIのイメージを定義する
- UIを実装する
- market contractと連携して売買機能を実装する

実際に開発を進めていく中でもう少し出てくるかもです。

**Comment by taijusanagi** [comment]
いったん下記のイメージです。

雛形を #82 で作っている @kusakabob と連携しつつお願いします。

先ほどの #67 で考えたようにもっとこうしたらいい、というようなことはどんどん考えていきたいので、何かあったら呼んでください。

- ざっくりしたフローのイメージ

<img width="898" alt="Screen Shot 2020-11-10 at 13 25 17" src="https://user-images.githubusercontent.com/38043569/98627719-2e8cb680-2358-11eb-887b-b92abc2e011e.png">


- UIのイメージ
<img width="676" alt="Screen Shot 2020-11-10 at 13 25 41" src="https://user-images.githubusercontent.com/38043569/98627753-3fd5c300-2358-11eb-9934-c45b5c02a250.png">

**Comment by cookunijs** [comment]
UI実装完了です。
